apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-ops
data:
  config.yml: |-
    global:
    route:
      receiver: alert-web-hooker
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: alert-web-hooker
      webhook_configs:
        - url: 'https://'
